### ISSUE TITLE
Getting KeyError(2) error, How can I solve it? 

### ISSUE THREAD

**Issue by neemashahbazi** [lzzppp/DERT#3]
Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/train.csv"
0% [############################# ] 100% | ETA: 00:00:00
Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/valid.csv"
0% [############################# ] 100% | ETA: 00:00:00
Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/test.csv"
0% [############################# ] 100% | ETA: 00:00:00WARNING:torchtext.legacy.data.iterator:The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.

Building vocabulary
0% [######] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
WARNING:torchtext.legacy.data.iterator:The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.

Computing principal components
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    train, validation, test = dm.data.process(
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/process.py", line 193, in process
    datasets = MatchingDataset.splits(
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/dataset.py", line 472, in splits
    datasets[0].compute_metadata(train_pca)  # Traindataset
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/dataset.py", line 246, in compute_metadata
    for batch in pyprind.prog_bar(train_iter,
  File "/home/nima/fairER/DERT/text_er/env/lib/python3.8/site-packages/pyprind/generator_factory.py", line 18, in generator_progress
    for item in iteritem:
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/iterator.py", line 39, in __iter__
    yield MatchingBatch(batch, self.train_info)
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 47, in __init__
    AttrTensor(
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in __new__
    [[raw_word_probs[w] for w in b] for b in data.data])
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in <listcomp>
    [[raw_word_probs[w] for w in b] for b in data.data])
  File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in <listcomp>
    [[raw_word_probs[w] for w in b] for b in data.data])
KeyError: tensor(2)

**Comment by lzzppp** [comment]
This is an error of the torch version, please install it according to the requirements.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lzzppp/DERT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 凌晨3:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lzzppp/DERT] Getting KeyError(2) error, How can I solve it?  (Issue #3)





 
Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/train.csv"
 0% [############################# ] 100% | ETA: 00:00:00
 Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/valid.csv"
 0% [############################# ] 100% | ETA: 00:00:00
 Reading and processing data from "/home/nima/fairER/DERT/text_er/dataset/mcan_dataset/dataset/Textual/WA/test.csv"
 0% [############################# ] 100% | ETA: 00:00:00WARNING:torchtext.legacy.data.iterator:The device argument should be set by using torch.device or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
 
Building vocabulary
 0% [######] 100% | ETA: 00:00:00
 Total time elapsed: 00:00:00
 WARNING:torchtext.legacy.data.iterator:The device argument should be set by using torch.device or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
 
Computing principal components
 Traceback (most recent call last):
 File "main.py", line 26, in 
 train, validation, test = dm.data.process(
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/process.py", line 193, in process
 datasets = MatchingDataset.splits(
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/dataset.py", line 472, in splits
 datasets[0].compute_metadata(train_pca)  # Traindataset
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/dataset.py", line 246, in compute_metadata
 for batch in pyprind.prog_bar(train_iter,
 File "/home/nima/fairER/DERT/text_er/env/lib/python3.8/site-packages/pyprind/generator_factory.py", line 18, in generator_progress
 for item in iteritem:
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/data/iterator.py", line 39, in iter
 yield MatchingBatch(batch, self.train_info)
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 47, in init
 AttrTensor(
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in new
 [[raw_word_probs[w] for w in b] for b in data.data])
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in 
 [[raw_word_probs[w] for w in b] for b in data.data])
 File "/home/nima/fairER/DERT/text_er/MCAN/mcan/batch.py", line 27, in 
 [[raw_word_probs[w] for w in b] for b in data.data])
 KeyError: tensor(2)
